language: java

git:
  depth: 1
  quiet: true

addons:
  sonarcloud:
    organization: "meta-attack-language"
    token:
      secure: "n9xhay1Juhh0Z1WQFl+Q6+0FVbnmeEwJHclL7kl5w4pRXCUN3pCSe/DpnWGoFSWsAu3yvIlrVptGNyb68Kwcv4gGy468rrx8hceXYjMbDOVHlIUvWYfsm7qrx2L+eMs7iw0tERiKX2E3qxOrNBCg9fQ5T7eBhP5KF4oextXyonAXRRSaxzNLqaAD8ABP9ahkuDFu30BGI0dGccCKMG7D4pffHOGNayLrbP1COY8pVgRtl2cDgzySVTlF4882nj/zo3vzT4of6i5J4zxuaaEMG56k6rRmFySfL4L6pdwYYhWGCeg9X6VPH388hoVs0acirtlc5stRcYuloc6Nda5HpJbQr4hhtzjd6sq8ZvrH8lkxaW9RTk0j7DD6/rcmE+VVZ/IWYoO+7YYJFFk+Anbir+p9hO3NA3PWjulJL1g2Eh5hMHuIG+A81Cyv2bpAK6yJwo03coh8C0knNkPwa8RoghE2UKagJGaZbFzoqHkrax5upuxRBSYwvRacp1vAAgnsGb1Xr84k7bghBB0eGNxGNMYINng2fkZCJMfChWd5GdlizQwtT7M5daTwCalky/XegYIBcRwDXYiUx131wkathvqs1rAQcQWMptWHHYqS2niCSWx2qAYPIgHK6BDfLIMHlf50ZvtFOkAW6jcpUWgvhIGYT9Khp90NitiwsmVhE8E="

before_install:
  - echo "Cloning maven-jlink-plugin..."
  - git clone --quiet --no-checkout https://github.com/apache/maven-jlink-plugin.git
  - cd maven-jlink-plugin
  - git checkout --quiet -b tmp d474b2d0c664faee2500fb3cb869898aca281b79
  - cd ..
  - echo "Cloning javapoet..."
  - git clone --quiet --depth 1 https://github.com/meta-attack-language/javapoet.git
  - echo "Cloning svgSalamander..."
  - git clone --quiet --depth 1 https://github.com/meta-attack-language/svgSalamander.git

install:
  - echo "Installing maven-jlink-plugin..."
  - cd maven-jlink-plugin
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - echo "Installing javapoet..."
  - cd ../javapoet
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - echo "Installing svgSalamander..."
  - cd ../svgSalamander/svg-core
  - mvn install --quiet --batch-mode --define maven.test.skip=true
  - cd ../..

before_script:
  - echo "Cleaning up cloned dependencies"
  - rm -rf maven-jlink-plugin
  - rm -rf javapoet
  - rm -rf svgSalamander

script:
  - echo "Installing mal..."
  - mvn clean install --batch-mode
  - echo "Installing mal.lib..."
  - cd mal.lib
  - mvn clean install --quiet --batch-mode
  - echo "Installing mal.cli..."
  - cd ../mal.cli
  - mvn clean install --quiet --batch-mode
  - echo "Installing mal.test..."
  - cd ../mal.test
  - mvn clean install --quiet --batch-mode
  - echo "Installing mal.img..."
  - cd ../mal.img
  - mvn clean install --quiet --batch-mode
  - echo "Installing mal-maven-plugin..."
  - cd ../mal-maven-plugin
  - mvn clean install --quiet --batch-mode
  - echo "Testing update_mal.py..."
  - cd ../update_mal
  - ./run-tests.sh
  - cd ..
  - mvn clean verify
  - mvn sonar:sonar --define sonar.java.coveragePlugin=jacoco --define sonar.dynamicAnalysis=reuseReports --define sonar.jacoco.reportPath="$PWD/mal.test/target/jacoco.exec" --define sonar.language=java
